"""Report renderer for bug_triage.

This module renders a :class:`~bug_triage.models.ReportOutput` into either
a human-readable Markdown document or a machine-readable JSON payload.  It
uses Jinja2 for the Markdown template and Rich for optional console output.

Public interface:
    - :class:`Reporter` — configurable renderer class.
    - :func:`render_report` — convenience wrapper around :class:`Reporter`.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from jinja2 import BaseLoader, Environment, TemplateNotFound
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.table import Table
from rich import box

from bug_triage.models import (
    IssueGroup,
    OutputFormat,
    ReportOutput,
    Severity,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Markdown template (inline so no extra file is needed for the reporter)
# ---------------------------------------------------------------------------

_MARKDOWN_TEMPLATE = """\
# Bug Triage Report

**Generated:** {{ metadata.generated_at.strftime("%Y-%m-%d %H:%M:%S") }} UTC
{% if metadata.repository %}
**Repository:** {{ metadata.repository }}
{% endif %}
{% if metadata.source_file %}
**Source File:** {{ metadata.source_file }}
{% endif %}
**LLM Model:** {{ metadata.llm_provider }} / {{ metadata.llm_model }}
**Total Issues Analysed:** {{ metadata.total_issues }}
**Issue Groups (after deduplication):** {{ metadata.total_groups }}

---
{% set severity_order = ["critical", "high", "medium", "low"] %}
{% set severity_emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"} %}
{% for sev in severity_order %}
{% set sev_groups = groups | selectattr("severity", "equalto", sev) | list %}
{% if sev_groups %}

## {{ severity_emoji.get(sev, "⚪") }} {{ sev | capitalize }} ({{ sev_groups | length }} group{{ "s" if sev_groups | length != 1 else "" }})
{% for group in sev_groups | sort(attribute="fix_order") %}

### Group {{ group.fix_order }} — {{ group.title }}

| Field | Value |
|-------|-------|
| **Severity** | {{ group.severity | capitalize }} |
| **Impact** | {{ group.impact_category | replace("_", " ") | title }} |
| **Priority Score** | {{ "%.1f" | format(group.priority_score) }} / 100 |
| **Est. Complexity** | {{ group.complexity | capitalize }} |
| **Fix Order** | #{{ group.fix_order }} |
| **Issues in Group** | {{ group.issue_ids | join(", ") | replace("", "#") }}{% for iid in group.issue_ids %}#{{ iid }}{% if not loop.last %}, {% endif %}{% endfor %} |
{% if group.canonical_issue_id %}
| **Canonical Issue** | #{{ group.canonical_issue_id }} |
{% endif %}
{% if group.tags %}
| **Tags** | {{ group.tags | join(", ") }} |
{% endif %}

{% if group.summary %}
> {{ group.summary }}
{% endif %}
{% if group.similar_closed_issue_ids %}

**Similar Closed Issues:** {{ group.similar_closed_issue_ids | join(", ") | replace("", "#") }}{% for iid in group.similar_closed_issue_ids %}#{{ iid }}{% if not loop.last %}, {% endif %}{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% if ungrouped_issue_ids %}

---

## ⚪ Ungrouped Issues

The following {{ ungrouped_issue_ids | length }} issue(s) could not be assigned to a group:
{{ ungrouped_issue_ids | join(", ") | replace("", "#") }}{% for iid in ungrouped_issue_ids %}#{{ iid }}{% if not loop.last %}, {% endif %}{% endfor %}
{% endif %}

---

*Report generated by [bug-triage](https://github.com/example/bug-triage)*
"""

# A cleaner template that avoids the awkward issue-ID formatting above.
_MARKDOWN_TEMPLATE = '''\
# Bug Triage Report

**Generated:** {{ metadata.generated_at.strftime("%Y-%m-%d %H:%M:%S") }} UTC
{% if metadata.repository %}
**Repository:** {{ metadata.repository }}
{% endif %}
{% if metadata.source_file %}
**Source File:** {{ metadata.source_file }}
{% endif %}
**LLM Model:** {{ metadata.llm_provider }} / {{ metadata.llm_model }}
**Total Issues Analysed:** {{ metadata.total_issues }}
**Issue Groups (after deduplication):** {{ metadata.total_groups }}

---
{% set severity_order = ["critical", "high", "medium", "low"] %}
{% set severity_emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"} %}
{% for sev in severity_order %}
{% set sev_groups = [] %}
{% for g in groups %}
{% if g.severity == sev %}
{% set _ = sev_groups.append(g) %}
{% endif %}
{% endfor %}
{% if sev_groups %}

## {{ severity_emoji.get(sev, "⚪") }} {{ sev | capitalize }} ({{ sev_groups | length }} group{{ "s" if sev_groups | length != 1 else "" }})
{% for group in sev_groups %}

### Fix #{{ group.fix_order }} — {{ group.title }}

**Severity:** {{ group.severity | capitalize }} | **Impact:** {{ group.impact_category | replace("_", " ") | title }} | **Priority Score:** {{ "%.1f" | format(group.priority_score) }}/100 | **Estimated Complexity:** {{ group.complexity | capitalize }}

**Issues in this group:** {% for iid in group.issue_ids %}#{{ iid }}{% if not loop.last %}, {% endif %}{% endfor %}
{% if group.canonical_issue_id %}
**Canonical Issue:** #{{ group.canonical_issue_id }}
{% endif %}
{% if group.tags %}
**Tags:** {{ group.tags | join(", ") }}
{% endif %}
{% if group.summary %}

> {{ group.summary }}
{% endif %}
{% if group.similar_closed_issue_ids %}

**Similar Closed Issues:** {% for iid in group.similar_closed_issue_ids %}#{{ iid }}{% if not loop.last %}, {% endif %}{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% if ungrouped_issue_ids %}

---

## ⚪ Ungrouped Issues

The following {{ ungrouped_issue_ids | length }} issue(s) could not be assigned to a group:
{% for iid in ungrouped_issue_ids %}#{{ iid }}{% if not loop.last %}, {% endif %}{% endfor %}
{% endif %}

---

*Report generated by [bug-triage](https://github.com/example/bug-triage)*
'''


# ---------------------------------------------------------------------------
# Severity display helpers
# ---------------------------------------------------------------------------

_SEVERITY_EMOJI: dict[str, str] = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
}

_SEVERITY_COLOUR: dict[str, str] = {
    "critical": "bold red",
    "high": "bold yellow",
    "medium": "yellow",
    "low": "green",
}

_SEVERITY_ORDER = ["critical", "high", "medium", "low"]


# ---------------------------------------------------------------------------
# Reporter class
# ---------------------------------------------------------------------------


class ReporterError(Exception):
    """Raised when the reporter encounters an unrecoverable rendering error."""


class Reporter:
    """Renders a :class:`~bug_triage.models.ReportOutput` to Markdown or JSON.

    The reporter supports two output modes:

    * **Markdown** — human-readable report rendered via a Jinja2 template.
    * **JSON** — machine-readable report serialised directly from the Pydantic
      model using its built-in ``model_dump`` method.

    It can also print a Rich-formatted summary to the terminal via
    :meth:`print_summary`.

    Args:
        output_format: The desired output format (``markdown`` or ``json``).
        console: A :class:`rich.console.Console` instance used for terminal
            output.  If ``None``, a default console is created.
        json_indent: Indentation level for JSON output.
    """

    def __init__(
        self,
        output_format: OutputFormat = OutputFormat.MARKDOWN,
        console: Optional[Console] = None,
        json_indent: int = 2,
    ) -> None:
        self.output_format = output_format
        self.console = console or Console()
        self.json_indent = json_indent
        self._jinja_env = self._build_jinja_env()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def render(self, report: ReportOutput) -> str:
        """Render the triage report to a string.

        Dispatches to :meth:`render_markdown` or :meth:`render_json` based on
        the configured ``output_format``.

        Args:
            report: The fully populated triage report to render.

        Returns:
            The rendered report as a string.

        Raises:
            ReporterError: If rendering fails for any reason.
        """
        if self.output_format == OutputFormat.JSON:
            return self.render_json(report)
        return self.render_markdown(report)

    def render_markdown(self, report: ReportOutput) -> str:
        """Render the report as a Markdown document.

        Args:
            report: The triage report to render.

        Returns:
            A Markdown string.

        Raises:
            ReporterError: If the Jinja2 template fails to render.
        """
        try:
            template = self._jinja_env.get_template("report.md.j2")
        except TemplateNotFound as exc:
            raise ReporterError(
                f"Markdown report template not found: {exc}"
            ) from exc

        # Sort groups by fix_order for deterministic rendering.
        sorted_groups = sorted(
            report.groups,
            key=lambda g: (g.fix_order if g.fix_order > 0 else 9999, -g.priority_score),
        )

        try:
            rendered = template.render(
                metadata=report.metadata,
                groups=sorted_groups,
                raw_issues=report.raw_issues,
                triage_results=report.triage_results,
                ungrouped_issue_ids=report.ungrouped_issue_ids,
            )
        except Exception as exc:
            raise ReporterError(
                f"Failed to render Markdown report: {exc}"
            ) from exc

        return rendered

    def render_json(self, report: ReportOutput) -> str:
        """Render the report as a JSON string.

        Serialises the :class:`~bug_triage.models.ReportOutput` Pydantic model
        to JSON, with datetime values converted to ISO-8601 strings.

        Args:
            report: The triage report to render.

        Returns:
            A JSON string.

        Raises:
            ReporterError: If JSON serialisation fails.
        """
        try:
            data = report.model_dump(mode="json")
            return json.dumps(data, indent=self.json_indent, ensure_ascii=False)
        except Exception as exc:
            raise ReporterError(
                f"Failed to serialise report to JSON: {exc}"
            ) from exc

    def save(
        self, report: ReportOutput, output_path: str | Path
    ) -> Path:
        """Render the report and write it to a file.

        Args:
            report: The triage report to render.
            output_path: Destination file path.

        Returns:
            The resolved :class:`pathlib.Path` that was written.

        Raises:
            ReporterError: If rendering or writing fails.
        """
        path = Path(output_path)
        content = self.render(report)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        except OSError as exc:
            raise ReporterError(
                f"Failed to write report to '{path}': {exc}"
            ) from exc
        logger.info("Report written to '%s'.", path)
        return path

    def print_summary(self, report: ReportOutput) -> None:
        """Print a Rich-formatted summary of the triage report to the console.

        This method writes directly to the configured :class:`rich.console.Console`
        instance.  It prints:

        * A header panel with metadata.
        * A table of issue groups sorted by fix order.
        * A footer note about ungrouped issues (if any).

        Args:
            report: The completed triage report.
        """
        self._print_header(report)
        if report.groups:
            self._print_groups_table(report)
        else:
            self.console.print(
                "[dim]No issue groups to display.[/dim]"
            )
        if report.ungrouped_issue_ids:
            self.console.print(
                f"\n[dim]⚪ {len(report.ungrouped_issue_ids)} ungrouped issue(s): "
                + ", ".join(f"#{i}" for i in report.ungrouped_issue_ids)
                + "[/dim]"
            )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _build_jinja_env() -> Environment:
        """Build a Jinja2 environment backed by the inline template string."""
        env = Environment(
            loader=_InlineTemplateLoader({"report.md.j2": _MARKDOWN_TEMPLATE}),
            autoescape=False,
            trim_blocks=True,
            lstrip_blocks=True,
        )
        return env

    def _print_header(self, report: ReportOutput) -> None:
        """Print the report header panel to the console."""
        meta = report.metadata
        lines: list[str] = []
        if meta.repository:
            lines.append(f"[bold]Repository:[/bold] {meta.repository}")
        if meta.source_file:
            lines.append(f"[bold]Source File:[/bold] {meta.source_file}")
        lines.append(
            f"[bold]LLM:[/bold] {meta.llm_provider} / {meta.llm_model}"
        )
        lines.append(
            f"[bold]Generated:[/bold] "
            f"{meta.generated_at.strftime('%Y-%m-%d %H:%M:%S')} UTC"
        )
        lines.append(
            f"[bold]Issues Analysed:[/bold] {meta.total_issues}  |  "
            f"[bold]Groups:[/bold] {meta.total_groups}"
        )
        self.console.print(
            Panel(
                "\n".join(lines),
                title="[bold cyan]🐛 Bug Triage Report[/bold cyan]",
                border_style="cyan",
                expand=False,
            )
        )

    def _print_groups_table(self, report: ReportOutput) -> None:
        """Print a Rich table of issue groups sorted by fix order."""
        table = Table(
            box=box.ROUNDED,
            show_header=True,
            header_style="bold magenta",
            expand=False,
            title="Issue Groups by Priority",
        )
        table.add_column("#", style="dim", width=3, justify="right")
        table.add_column("Severity", min_width=8)
        table.add_column("Score", justify="right", width=6)
        table.add_column("Complexity", width=10)
        table.add_column("Issues", width=10)
        table.add_column("Title")

        sorted_groups = sorted(
            report.groups,
            key=lambda g: (g.fix_order if g.fix_order > 0 else 9999, -g.priority_score),
        )

        for group in sorted_groups:
            sev_str = group.severity.value
            colour = _SEVERITY_COLOUR.get(sev_str, "white")
            emoji = _SEVERITY_EMOJI.get(sev_str, "⚪")
            issue_ids_str = ", ".join(f"#{i}" for i in group.issue_ids)
            table.add_row(
                str(group.fix_order),
                f"[{colour}]{emoji} {sev_str.capitalize()}[/{colour}]",
                f"{group.priority_score:.1f}",
                group.complexity.value.capitalize(),
                issue_ids_str,
                group.title,
            )

        self.console.print(table)


# ---------------------------------------------------------------------------
# Inline Jinja2 loader
# ---------------------------------------------------------------------------


class _InlineTemplateLoader(BaseLoader):
    """A Jinja2 loader that serves templates from an in-memory dictionary.

    This avoids the need to have a separate template file on disk for the
    Markdown report template, keeping the reporter self-contained.

    Args:
        templates: Mapping of template name → template source string.
    """

    def __init__(self, templates: dict[str, str]) -> None:
        self._templates = templates

    def get_source(
        self, environment: Environment, template: str
    ) -> tuple[str, Optional[str], Any]:
        """Return the template source, filename, and uptodate callable."""
        if template not in self._templates:
            raise TemplateNotFound(template)
        source = self._templates[template]
        # Return (source, filename, uptodate).  filename=None and
        # uptodate=None (always reload) is fine for inline templates.
        return source, None, lambda: True


# ---------------------------------------------------------------------------
# Convenience function
# ---------------------------------------------------------------------------


def render_report(
    report: ReportOutput,
    output_format: OutputFormat = OutputFormat.MARKDOWN,
    output_path: Optional[str | Path] = None,
    print_to_console: bool = True,
    console: Optional[Console] = None,
    json_indent: int = 2,
) -> str:
    """Render a triage report and optionally save it and/or print a summary.

    This is the main convenience entry-point for the reporter subsystem.  It
    creates a :class:`Reporter`, renders the report, optionally writes it to
    disk, and optionally prints a Rich summary to the terminal.

    Args:
        report: The completed :class:`~bug_triage.models.ReportOutput` to
            render.
        output_format: Desired output format (``markdown`` or ``json``).
        output_path: If provided, the rendered report is written to this path.
        print_to_console: If ``True``, print a Rich summary table to stdout.
        console: Optional :class:`rich.console.Console` instance to use.  A
            default console is created if ``None``.
        json_indent: JSON indentation level (only relevant for JSON format).

    Returns:
        The rendered report as a string.

    Raises:
        ReporterError: If rendering or file I/O fails.
    """
    reporter = Reporter(
        output_format=output_format,
        console=console or Console(),
        json_indent=json_indent,
    )

    rendered = reporter.render(report)

    if output_path is not None:
        reporter.save(report, output_path)

    if print_to_console:
        reporter.print_summary(report)

    return rendered
